name: Test
on:
  workflow_dispatch:

jobs:
  empty_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Test
      run: |
        response=$(curl -s https://reqres.in/api/users/2 | jq -r '.data | "- id: \(.id), email: \(.email)"')
        echo '### The response fo Test is 🚀' >> $GITHUB_STEP_SUMMARY
        echo "$response" >> $GITHUB_STEP_SUMMARY
